extract = 'total_dyn_inst: (\d+)'
benchmarks = '../benchmarks/**/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.to_ssa]
pipeline = [
    "bril2json",
    "../build/coretest/ssa-main",
    "brili -p {args}",
]
