extract = 'total_dyn_inst: (\d+)'
benchmarks = '../benchmarks/**/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.to_ssa_with_opt]
pipeline = [
    "bril2json",
    "../build/coretest/to-ssa-main",
    "brili -p {args}",
]

[runs.to_ssa_no_opt]
pipeline = [
    "bril2json",
    "../build/coretest/to-ssa-main -O",
    "brili -p {args}",
]
