extract = 'total_dyn_inst: (\d+)'
benchmarks = '../benchmarks/mem/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]


[runs.gc]
pipeline = [
    "bril2json",
    "brili -p {args}",
]