extract = 'total_dyn_inst: (\d+)'
benchmarks = '../benchmarks/core/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.tdce]
pipeline = [
    "bril2json",
    "../build/l3/tdce",
    "brili -p {args}",
]

[runs.lvn_tdce]
pipeline = [
    "bril2json",
    "../build/l3/tdce",
    "python lvn.py",
    "../build/l3/tdce",
    "brili -p {args}",
]
